// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class Product
{
    public int Productid { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Unitprice { get; set; }

    public int Categoryid { get; set; }

    public virtual Category Category { get; set; }
}