// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class User
{
    public int Userid { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }
}